# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_all_files": "00_core.ipynb",
         "download_image": "01_imgtools.ipynb",
         "download_images": "01_imgtools.ipynb",
         "verify_image_tf": "01_imgtools.ipynb",
         "verify_images": "01_imgtools.ipynb",
         "random_crop": "02_tftools.ipynb",
         "central_crop": "02_tftools.ipynb",
         "random_flip": "02_tftools.ipynb",
         "random_brightness": "02_tftools.ipynb",
         "random_contrast": "02_tftools.ipynb",
         "random_rotate": "02_tftools.ipynb",
         "get_label": "02_tftools.ipynb",
         "train_test_split": "02_tftools.ipynb",
         "process_img_path": "02_tftools.ipynb",
         "process_img_bytes": "02_tftools.ipynb",
         "read_img_dataset": "02_tftools.ipynb",
         "show_batch": "02_tftools.ipynb",
         "plot_history": "02_tftools.ipynb"}

modules = ["core.py",
           "imgtools.py",
           "tftools.py"]

git_url = "https://github.com/yoke2/suptools/tree/master/"

def custom_doc_links(name): return None
